dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /'
      key_url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key'
    packages:
    - buildah
language: go
go:
- 1.14.x
cache:
  directories:
  - "${GOPATH}/pkg/mod"
  - "${GOPATH}/pkg/sumdb"
env:
  global:
  - GO111MODULE: 'on'
  - RELAY_EMAIL: team-relay-ops@puppet.com
  - secure: QL8vS5o6H3/WyqelaJprcwUA/troTk67YeTs0m362327EsdQXEVnk0dlCcT+j460ALGgJ8l+j+Ywx9StFwx5FWOdvA02QMyiM1rNXtdJREACQe+3rODxwaoc+wMiX31Nnahg5uu/w3nXjY6wZpNto6pISZaSHxblm90uAGSlCKDd5PeEkH0CkQMDgN7JqwYeWohqXgIhkq/qTmnbNfwE4UTXo3/o3X9JqrZJV1aH1R0HKhH2qCM9BxldvnTVp36444qM8r/UGiZEjoqp2u1XZ47wmRMdKVcSSw013n6yhdT9vrGaCPKrGXVQt00/lU9TpCW0SR5CPsyMPhqIRI9EDKT3WwltV/t0x1ofuP3G2yEfoFxsktxQs4tF099u4QnTL74vat7KnnCX9QHkzONk0bUv9SzF8a9Z0bO9SDfG/pV+4f9DL6dTiC2Tp06kr7VEHkdURe/Xg+t/CzZ64derhmDxciiI+4wqq8xhktFcdMEBiRxs84ToccohzJrYyLFJ9HowKp4EIb8UYW5f5umN6iLUN/dNqyU8BXLo3zhw9plIT6GT4hlFdX8mFTKTAIkSUlezYzOlR2/j6x3yd3RWAFDFdGpQtTh3C306cvzkr0Ng2f+H3qUZBX8MskK/oK9sOM8nv7c9DLZOTxOdHPfDPm4751uhqZb5t+GTCE3va1Q=
install: skip
jobs:
  include:
  - stage: test
    before_script:
    - docker build -t localhost/kindest/node-gvisor hack/kind-gvisor/
    - ( cd; GO111MODULE=on go get sigs.k8s.io/kind@v0.9.0 )
    - export KUBECONFIG=/tmp/kubeconfig-kind
    - kind create cluster --image localhost/kindest/node-gvisor --config hack/kind-gvisor/config.yaml
    script:
    - |
      while sleep 9m; do
        echo -e '--- OUT-OF-BAND: Waiting...' >&2
      done &
    - RELAY_TEST_E2E_KUBECONFIG="${KUBECONFIG}" RELAY_TEST_E2E_GVISOR_HANDLER=runsc ./scripts/ci test
    - kill %1
  - stage: build
    before_script:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com |
      bash; fi
    - source "$HOME"/google-cloud-sdk/path.bash.inc
    - openssl aes-256-cbc -K $encrypted_35392154f715_key -iv $encrypted_35392154f715_iv
      -in scripts/nebula-gcloud-service-account.json.enc -out scripts/nebula-gcloud-service-account.json
      -d
    - gcloud auth activate-service-account --key-file scripts/nebula-gcloud-service-account.json
    - gcloud --quiet auth configure-docker
    script:
    - "./scripts/ci build"
    - "./scripts/ci release"
  - stage: deploy
    script:
    - "./scripts/ci deploy"
