apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay-install-operator
  namespace: relay-system
  labels:
    app.kubernetes.io/name: relay-install
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relay-install-operator-relaycores
  labels:
    app.kubernetes.io/name: relay-install
    app.kubernetes.io/component: controller
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.relay.sh
  resources:
  - relaycores
  - relaycores/status
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: relay-install-operator-relaycores
  labels:
    app.kubernetes.io/name: relay-install
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: relay-install-operator-relaycores
subjects:
- kind: ServiceAccount
  name: relay-install-operator
  namespace: relay-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-install-operator
  namespace: relay-system
  labels:
    app.kubernetes.io/name: relay-install
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: relay-install
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: relay-install
        app.kubernetes.io/component: controller
    spec:
      containers:
      - name: controller
        image: relaysh/relay-install-operator:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      serviceAccountName: relay-install-operator
